import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import { ReduxProvider } from "./redux/ReduxProvider";
import ProductLoader from "./components/product-loader/productLoader";
import UserInitializer from "./components/user-initializer/userInitializer";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Tengo Store</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <ProductLoader />
          <UserInitializer />
          <Navbar />
          <main className="p-8 mt-20">
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}

